# Generated by Django 5.2.4 on 2025-07-31 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_accessibility_details_and_more'),
        ('users', '0004_profile_can_post_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_post_blog', 'Can post blog posts')]},
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_post_blog',
            field=models.BooleanField(default=False, help_text='Can post blog posts'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_promoted', 'User Promoted'), ('user_demoted', 'User Demoted'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_profile_updated', 'User Profile Updated'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('group_renamed', 'Group Renamed'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted'), ('event_cancelled', 'Event Cancelled'), ('event_activated', 'Event Activated'), ('notification_sent', 'Notification Sent'), ('bulk_notification_sent', 'Bulk Notification Sent'), ('banner_updated', 'Site Banner Updated'), ('banner_disabled', 'Site Banner Disabled'), ('blog_post_created', 'Blog Post Created'), ('blog_post_deleted', 'Blog Post Deleted'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional data related to the action')),
                ('event', models.ForeignKey(blank=True, help_text='Event involved in the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('group', models.ForeignKey(blank=True, help_text='Group involved in the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.group')),
                ('target_user', models.ForeignKey(blank=True, help_text='User who was affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='users_audit_user_id_4b4ca5_idx'), models.Index(fields=['action', 'timestamp'], name='users_audit_action_962101_idx'), models.Index(fields=['group', 'timestamp'], name='users_audit_group_i_90ab75_idx'), models.Index(fields=['target_user', 'timestamp'], name='users_audit_target__511392_idx')],
            },
        ),
    ]
